[2025-05-20T09:21:17.105+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T09:21:17.110+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_minio_to_spark.kafka_consumer scheduled__2025-05-19T16:00:00+00:00 [queued]>
[2025-05-20T09:21:17.112+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_minio_to_spark.kafka_consumer scheduled__2025-05-19T16:00:00+00:00 [queued]>
[2025-05-20T09:21:17.113+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 4
[2025-05-20T09:21:17.116+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): kafka_consumer> on 2025-05-19 16:00:00+00:00
[2025-05-20T09:21:17.118+0000] {standard_task_runner.py:72} INFO - Started process 483 to run task
[2025-05-20T09:21:17.120+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_minio_to_spark', 'kafka_consumer', 'scheduled__2025-05-19T16:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/testlog_ml.py', '--cfg-path', '/tmp/tmpbvlxn6do']
[2025-05-20T09:21:17.121+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask kafka_consumer
[2025-05-20T09:21:17.138+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_to_minio_to_spark.kafka_consumer scheduled__2025-05-19T16:00:00+00:00 [running]> on host 6a89a243c286
[2025-05-20T09:21:17.232+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_minio_to_spark' AIRFLOW_CTX_TASK_ID='kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T16:00:00+00:00'
[2025-05-20T09:21:17.232+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-20T09:21:17.238+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-05-20T09:21:17.242+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=host.docker.internal:9092 <checking_api_versions_recv> [IPv4 ('192.168.65.254', 9092)]>: Broker version identified as 2.6
[2025-05-20T09:21:17.243+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>: Connection complete.
[2025-05-20T09:21:17.243+0000] {subscription_state.py:177} INFO - Updating subscribed topics to: ('userlog',)
[2025-05-20T09:21:17.243+0000] {logging_mixin.py:190} INFO - ‚úÖ consumer started, waiting for messages....
[2025-05-20T09:21:17.246+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=1 host=172.16.24.224:9092 <connecting> [IPv4 ('172.16.24.224', 9092)]>: connecting to 172.16.24.224:9092 [('172.16.24.224', 9092) IPv4]
[2025-05-20T09:21:17.350+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=1 host=172.16.24.224:9092 <connected> [IPv4 ('172.16.24.224', 9092)]>: Connection complete.
[2025-05-20T09:21:17.350+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>: Closing connection. 
[2025-05-20T09:21:17.458+0000] {cluster.py:400} INFO - Coordinator for group/tospark is ('coordinator-1', '172.16.24.224', 9092, None)
[2025-05-20T09:21:17.458+0000] {base.py:769} INFO - Discovered coordinator coordinator-1 for group tospark
[2025-05-20T09:21:17.459+0000] {base.py:820} INFO - Starting new heartbeat thread
[2025-05-20T09:21:17.459+0000] {consumer.py:362} INFO - Revoking previously assigned partitions () for group tospark
[2025-05-20T09:21:17.460+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=coordinator-1 host=172.16.24.224:9092 <connecting> [IPv4 ('172.16.24.224', 9092)]>: connecting to 172.16.24.224:9092 [('172.16.24.224', 9092) IPv4]
[2025-05-20T09:21:17.566+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=coordinator-1 host=172.16.24.224:9092 <connected> [IPv4 ('172.16.24.224', 9092)]>: Connection complete.
[2025-05-20T09:21:17.673+0000] {base.py:524} INFO - (Re-)joining group tospark
[2025-05-20T09:21:17.676+0000] {base.py:524} INFO - (Re-)joining group tospark
[2025-05-20T09:21:20.682+0000] {base.py:587} INFO - Elected group leader -- performing partition assignments using range
[2025-05-20T09:21:20.686+0000] {base.py:401} INFO - Successfully joined group tospark with generation 11
[2025-05-20T09:21:20.687+0000] {subscription_state.py:246} INFO - Updated partition assignment: [('userlog', 0)]
[2025-05-20T09:21:20.687+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('userlog', 0),) for group tospark
[2025-05-20T09:21:20.724+0000] {logging_mixin.py:190} INFO - üì• Received: page:movie_detail
[2025-05-20T09:21:20.724+0000] {logging_mixin.py:190} INFO - ‚ùå Failed to process message: OffsetAndMetadata.__new__() missing 1 required positional argument: 'leader_epoch'
[2025-05-20T09:21:20.725+0000] {logging_mixin.py:190} INFO - ‚ùå DAG failed due to : OffsetAndMetadata.__new__() missing 1 required positional argument: 'leader_epoch'
[2025-05-20T09:21:20.725+0000] {base.py:834} INFO - Stopping heartbeat thread
[2025-05-20T09:21:23.727+0000] {base.py:1037} WARNING - Heartbeat thread did not fully terminate during close
[2025-05-20T09:21:23.728+0000] {base.py:865} INFO - Leaving consumer group (tospark).
[2025-05-20T09:21:23.736+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=1 host=172.16.24.224:9092 <connected> [IPv4 ('172.16.24.224', 9092)]>: Closing connection. 
[2025-05-20T09:21:23.741+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=coordinator-1 host=172.16.24.224:9092 <connected> [IPv4 ('172.16.24.224', 9092)]>: Closing connection. 
[2025-05-20T09:21:23.746+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/testlog_ml.py", line 144, in kafka_consumer
    raise e
  File "/opt/airflow/dags/testlog_ml.py", line 113, in kafka_consumer
    raise e
  File "/opt/airflow/dags/testlog_ml.py", line 110, in kafka_consumer
    consumer.commit(offsets={tp: OffsetAndMetadata(msg.offset + 1, None)})
TypeError: OffsetAndMetadata.__new__() missing 1 required positional argument: 'leader_epoch'
[2025-05-20T09:21:23.762+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_to_minio_to_spark, task_id=kafka_consumer, run_id=scheduled__2025-05-19T16:00:00+00:00, execution_date=20250519T160000, start_date=20250520T092117, end_date=20250520T092123
[2025-05-20T09:21:23.773+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-20T09:21:23.776+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task kafka_consumer (OffsetAndMetadata.__new__() missing 1 required positional argument: 'leader_epoch'; 483)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/testlog_ml.py", line 144, in kafka_consumer
    raise e
  File "/opt/airflow/dags/testlog_ml.py", line 113, in kafka_consumer
    raise e
  File "/opt/airflow/dags/testlog_ml.py", line 110, in kafka_consumer
    consumer.commit(offsets={tp: OffsetAndMetadata(msg.offset + 1, None)})
TypeError: OffsetAndMetadata.__new__() missing 1 required positional argument: 'leader_epoch'
[2025-05-20T09:21:23.799+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-20T09:21:23.894+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T09:21:23.895+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
